// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"dgb/meter.aggregation/internal/application"
	"dgb/meter.aggregation/internal/configuration"
)

// Injectors from wire.go:

func CreateApi() *application.Api {
	configurationConfiguration := configuration.NewConfig()
	response := application.NewResponse(configurationConfiguration)
	middleware := application.NewMiddleware(response, configurationConfiguration)
	elecApi := application.NewElecApi(response, configurationConfiguration, middleware)
	oilApi := application.NewOilApi(response, configurationConfiguration, middleware)
	api := application.NewApi(response, elecApi, oilApi, configurationConfiguration, middleware)
	return api
}
